baseURL = "/"
languageCode = "en-us"
title = "Lambda Cove"
theme = "hugo-xmin"

[params]
footer = """[Email](mailto:blevy@protonmail.com)
| [GitHub](https://github.com/io12)
| [crates.io](https://crates.io/users/io12)
| [ArchWiki](https://wiki.archlinux.org/)"""

[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3
[[menu.main]]
name = "Atom Feed"
url = "/index.xml"
